name: Environment Application Setup

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "IP Address of Server to Configure"
        required: true
        type: string

      applist:
        description: "List of packages to be installed on new server"
        required: true
        type: string  
  workflow_call:
    inputs:
      ip:
        description: "IP Address of Server to Configure"
        required: true
        type: string

      applist:
        description: "List of packages to be installed on new server"
        required: true
        type: string


jobs:
  LoginToServer:
    name: Login to the server created  
    runs-on: ubuntu-latest
    steps:
      - name: Run login command
        shell: bash
        run: |
           echo "${{ secrets.SEP_29_KEY }}" > private_key && chmod 600 private_key
           ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ inputs.ip }}
           sudo apt update -y && sudo apt upgrade -y

    
  InstallAnsible:
    name: Install Ansible  
    needs: LoginToServer
    runs-on: ubuntu-latest  
    steps:
      - name: Installing Ansible
        shell: bash
        run: |
          sudo su
          apt install ansible -y

  ConfigureSSH:
    name: Configure SSH on server
    needs: LoginToServer
    runs-on: ubuntu-latest
    steps:
      - name: generate SSH Key
        run: sh "echo| echo| echo| ssh-keygen"
      
      - name: get the key and add in Authorization Keys file
        run: sh "cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys"


  InstallApplications:
    name: Install JDK
    needs: LoginToServer
    runs-on: ubuntu-latest
    steps:
      - name: Install jdk
        run: sh "apt install openjdk-17-jdk -y"
