name: Environment Configure

on: 
  workflow_dispatch:
    inputs:
      AutoApprove:
        description: 'autoApprove'
        required: true
        default: false
        type: choice
        options:
          - true
          - false
      
      Action:
        description: Choose what you want to do
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy



jobs:

  deploy:
    name: Environment Provision
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v4
      name: Checkout Repository
  
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
      name: Configure the AWS connection

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        terraform init

    - name: Terraform Plan
      id: Plan
      shell: bash
      run: |
        terraform plan

    - name: Terraform Apply/Destroy
      id: Apply-Destroy
      shell: bash
      run: |
        terraform ${{ inputs.Action }} -auto-approve

    # - name: Get the IP Address of Instance Created
    #   id: get-IP
    #   shell: bash
    #   run: |
    #     cat public_ips.txt

    - name: envrionment configuration
      uses: environment_installation.yaml@main
      with:
        ip: $( cat public_ips.txt)
        applist: "docker.io"
